
/**
 * This file was generated by EverDev.
 * EverDev is a part of EVER OS (see https://everos.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
pragma copyleft 1, 0x0;

// This is class that describes you smart contract.
contract Contract {
    uint32 timestamp;

    // Updates variable `timestamp` with current blockchain time.
    function touch() external {
        // Each function that accepts external message must check that
        // message is correctly signed.
        require(msg.pubkey() == tvm.pubkey(), 102);
        // Tells to the TVM that we accept this message.
        tvm.accept();
        // Update timestamp
        timestamp = now;
    }
}
