#!/bin/sh
set -x
set -e

export Q_HOT=http://127.0.0.1:8529
export Q_REQUESTS_MODE=rest
export Q_REQUESTS_SERVER=http://127.0.0.1
export Q_HOST=127.0.0.1
export Q_PORT=4000
export Q_QUERY_WAIT_FOR_PERIOD=10
export Q_CHAIN_RANGES_VERIFICATION=http://127.0.0.1:8529
export Q_SLOW_QUERIES=enable

cd /home/node/ever-q-server
exec node index.js
